language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

before_install:
  - chmod +x gradlew



before_deploy:
  - mkdir -p before_deploy
  - cp scripts/*.sh before_deploy/
  - cp appspec.yml before_deploy/
  - cp build/libs/*.jar before_deploy/
  - cd before_deploy && zip -r before_deploy *
  - cd ../ && mkdir -p deploy
  - mv before_deploy/before_deploy.zip deploy/freelec-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: freelec-springboot-build-yoon
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: freelec-springboot-build-yoon
    key: freelec-springboot2-webservice.zip
    bundle_type: zip
    application: freelec-sprintboot2-webservice
    deployment_group: freelec-springboot2-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - rival15@naver.com