language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

before_install:
  - chmod +x gradlew



before_deploy:
  - zip -r freelec-sprintboot2-webservice *
  - mkdir -p deploy
  - mv freelec-sprintboot2-webservice.zip deploy/freelec-sprintboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: @AWS_SECRET_KEY

    bucket: freelec-sprintboot-build-yoon
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - rival15@naver.com